import { Movie } from "@/modules/anime/movie/movie";
import type { Metadata } from "next";
import React from 'react'
export const metadata: Metadata = {
  title: "streaming",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Movie/>
  )
}

export default page