import { AddNew } from "@/modules/anime/movie/add-new/add-new";
import type { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "streaming",
  description: "Generated by create next app",
};

const page = () => {
  return <AddNew />;
};

export default page;
